# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Bootcamp 2019
tagline:
url:              https://princetonuniversity.github.io/PUbootcamp2019
baseurl:          '/PUbootcamp2019'
author:
  name:           Gabe Perez-Giz
  url:            https://github.com/gabeclass/
  email:          perezgiz@princeton.edu
plugins:
  - jekyll-redirect-from

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/PrincetonUniversity/PUbootcamp2019
  code:           https://github.com/PrincetonUniversity/PUbootcamp2019
pages_list:
  Agenda:       'agenda'
  Registration: 'registration'
  About:        'about'
